# Generated by Django 5.1.3 on 2024-12-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='required_amount_to_use_coupon',
            field=models.PositiveIntegerField(default=2000),
            preserve_default=False,
        ),
    ]
